Adjust phrasing of principles
w3ctag/ethical-web-principles pull request #124
Opened 2024-06-12 20:17 UTC by mnot

This is a minimal suggestion to reword the section titles to more clearly communicate that these are aspirations, not necessarily statements of fact.

Fixes #121.

2024-06-13 04:39 UTC, martinthomson approved these changes
One possible tweak

2024-06-13 04:39 UTC, martinthomson commented on index.html
> +An ethical web is an environmentally sustainable platform
```suggestion
An ethical web is environmentally sustainable
```

2024-06-13 06:21 UTC, hober requested changes
I really dislike the use of the phrase "an ethical web" in this PR. It implies that there's more than one web, some of which are ethical and some of which are not. It makes the "There is one web" principle incoherent, and doesn't seem to enhance the clarity of the document elsewhere.

2024-06-13 22:22 UTC, mnot commented
Oh, that's a shame - I really like this, because it's highlighting that there are multiple potential future Webs, and we can steer (to some degree) between them. I don't see the problem with "one web".

Possible alternatives:

1. Change them to a form like "The ethical web enables freedom of expression."
2. Change them to a form like "To be ethical, the web should enable freedom of expression."
3. Change them to a form like "The web should enable freedom of expression."

Thoughts?

2024-07-18 17:50 UTC, torgo commented
We agreed to close this PR today as we don't agree this is the right wording.

2024-07-18 17:50 UTC, closed without merging