Addition to sustainability
w3ctag/ethical-web-principles pull request #47
Opened 2021-09-14 08:21 UTC by rhiaro

Captures the essence of https://github.com/w3ctag/ethical-web-principles/pull/31 but in one sentence

2021-09-14 08:25 UTC, torgo commented on index.html
> +through maintaining backward compatibility,
```suggestion
through maintaining compatibility,
```

2021-09-14 08:27 UTC, torgo commented on index.html
> +as well as minimizing the data storage needs of applications.
```suggestion
as well as minimizing data storage needs.
```

2021-09-14 08:28 UTC, torgo requested changes
made changes as discussed in our f2f breakout

2021-09-14 08:28 UTC, torgo approved these changes

2021-09-14 08:29 UTC, rhiaro commented
Does this look okay to you, @ricjhill ?

2021-09-14 14:15 UTC, cynthia commented
Personal thought - I think the a nuance regarding where the data is stored is lost in this summary. It reads is if the 'device' is a continued subject, while the original wording probably implied "anywhere". (in particular, I assume it implies a data warehouse/lake of some form)

2021-09-14 14:15 UTC, cynthia approved these changes

2021-09-29 22:58 UTC, OR13 commented on index.html
> +as well as minimizing data storage needs.
```suggestion
as well as minimizing data storage and processing requirements.
```

2021-10-05 08:09 UTC, hadleybeeman approved these changes

2021-10-05 08:10 UTC, merged