Make each principle a subsection, fixes #33
w3ctag/ethical-web-principles pull request #49
Opened 2021-09-14 11:03 UTC by rhiaro

Keeps the ids the same so existing links to specific principles won't break.

2021-09-29 18:02 UTC, hober approved these changes
Looks good to me!

2021-09-29 22:47 UTC, jyasskin commented on index.html
> +  <p>
You should be able to omit the `<p>`s since you have markdown enabled. Just be sure to have a blank line around paragraphs.

2021-09-29 22:47 UTC, jyasskin commented on index.html
> +  <h3 id="oneweb" data-export="">
You should add `data-dfn-type=dfn` so this is still recognized as a definition, per https://tabatkins.github.io/bikeshed/#dfn-contract. Respec still doesn't handle internal [==] references to header definitions, but I think other specs will be able to find it.

2021-09-29 23:02 UTC, OR13 requested changes
dfn should be preserved per @jyasskin comments.

2021-10-06 15:33 UTC, torgo approved these changes
looks good!

2021-10-06 15:34 UTC, hadleybeeman approved these changes

2021-10-06 15:34 UTC, merged